name: flamingo
description: Live voice, video reels and feed
publish_to: 'none'

version: 1.0.1+80

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  #Default
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.5
  file_picker: ^8.0.6

  #Images
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_cropper: ^9.0.0
  blur: ^3.1.0
  video_editor: ^3.0.0
  wechat_camera_picker: ^4.3.7
  wechat_assets_picker: ^9.4.2
  flutter_image_compress: ^2.4.0
  mime: ^1.0.4
  preload_page_view: ^0.2.0
  like_button: ^2.0.5
  loading_animation_widget: ^1.2.0+4
  sliding_clipped_nav_bar: ^3.1.0+4
  path_provider: ^2.1.3
  video_player: ^2.9.5
  flutter_sound: ^9.9.5
  flutter_slider_drawer: ^2.1.3
  flutter_app_version_checker: ^0.3.2
  image_picker: ^1.0.4
  custom_zoom_widget: ^0.0.3
  video_thumbnail: ^0.5.3
  video_compress: ^3.1.2
  photo_manager_image_provider: ^2.1.0
  image_picker_web: ^3.1.1
  universal_io: ^2.2.2
  encrypt: ^5.0.3

  #Backend
  parse_server_sdk_flutter: ^9.0.0

  #State management
  get: ^4.6.6

  #Utilities
  easy_localization: ^3.0.7
  webview_flutter: ^4.2.1
  url_launcher: ^6.1.11
  universal_platform: ^1.1.0
  devicelocale: ^0.7.1
  url_strategy: ^0.2.0
  permission_handler: ^11.3.1
  share_plus: ^7.0.2
  stop_watch_timer: ^2.0.0
  fade_shimmer: ^2.2.0
  calendar_date_picker2: ^0.5.2
  circular_menu: ^2.0.1
  flutter_keyboard_visibility: ^5.4.1
  text_scroll: ^0.2.0
  emoji_picker_flutter: ^4.3.0
  flip_card: ^0.7.0
  flutter_animation_progress_bar: ^2.3.1
  flutter_cache_manager: ^3.3.0
  in_app_review: ^2.0.6
  auto_size_text_plus: ^3.0.1
  vibration: ^3.1.3
  quickalert: ^1.0.2
  dropdown_button2: ^2.3.9
  linear_progress_bar: ^1.1.0
  device_info_plus: ^11.3.0
  flutter_branch_sdk: ^8.4.0
  js: ^0.7.1

  sticky_grouped_list: ^3.1.0

  iban: ^1.0.1
  wakelock_plus: ^1.2.10
  whatsapp_unilink: ^2.1.0
  keyboard_attachable: ^2.1.0
  just_audio: ^0.9.34

  #Story
  advstory: ^0.2.1
  story: ^1.1.0

  #Color Picker
  flex_color_picker: ^3.3.0

  #Text for Stories text
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.1

  #Live Streaming
  zego_uikit: ^2.28.11
  zego_uikit_prebuilt_live_streaming: ^3.13.15
  zego_uikit_signaling_plugin: ^2.8.11
  zego_uikit_prebuilt_live_audio_room: ^3.15.9
  zego_uikit_prebuilt_call: ^4.16.27

  #Geo data and phone helper
  pin_code_fields: ^8.0.1
  geolocator: ^9.0.2
  geocoding: ^3.0.0
  location: ^7.0.0

  #Animations and icons
  #flutter_icons: ^1.1.0
  #lottie: ^2.3.2
  lottie: ^1.4.2
  svgaplayer_flutter_rhr: ^2.2.1
  transparent_image: ^2.0.1

  #Firebasemm
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  firebase_performance: ^0.10.0+8
  firebase_crashlytics: ^4.1.3
  firebase_auth_web: ^5.13.2
  firebase_auth_platform_interface: ^7.4.7

  #web
  web: ^1.0.0

  #push notifications
  another_flushbar: ^1.12.30
  onesignal_flutter: ^5.3.0
  #flutter_local_notifications: ^18.0.0

  #Social login
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3

  #payments:
  purchases_flutter: ^8.7.2


  # fake name
  faker: ^2.1.0

  #Animation
  flutter_animate: ^4.5.0

  #Ads
  google_mobile_ads: ^5.2.0
  app_tracking_transparency: ^2.0.4

  #video editing
  uuid: ^4.4.0

  #Libraries
  xml: ^6.3.0
  flutter_linkify: ^6.0.0
  marquee: ^2.2.3

  #See more or less Text
  expandable_text: ^2.3.0

  #Ads in Videos
  interactive_media_ads: ^0.2.1

  camera: ^0.10.0
  cached_video_player_plus: ^3.0.3

  gallery_saver_plus: ^3.2.4 #save Videos

dev_dependencies:
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/svg/
    - assets/lotties/
    - assets/video/
    - assets/icons/
    - assets/countries/

dependency_overrides:
  package_info_plus: ^4.1.0
  uuid: ^3.0.7
  parse_server_sdk: ^6.2.0
  web: ^0.5.1
  #parse_server_sdk: ^7.0.0
  js: ^0.6.3
  dio: ^5.3.2
  intl: ^0.18.1
  http: ^1.0.0
  win32: ^5.4.0
  photo_manager: ^3.6.4
  vibration: ^3.1.3

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/ic_logo_white.png
  #branding: assets/branding-production.png
  color_dark: "#000000"
  image_dark: assets/images/ic_logo_white.png
  #branding_dark: assets/branding-production.png
  android: true
  ios: true

  android_12:
    image: assets/images/ic_logo_white.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/ic_logo_white.png
    icon_background_color_dark: "#000000"
    android: true

  web: true