// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7QK9MtmtjM_vtsr5v6bPpEM099MX0XT8',
    appId: '1:419482297256:web:6d844e15fad4475f0af39d',
    messagingSenderId: '419482297256',
    projectId: 'flamingotar-32ba6',
    authDomain: 'flamingotar-32ba6.firebaseapp.com',
    storageBucket: 'flamingotar-32ba6.firebasestorage.app',
    measurementId: 'G-GB936FZ0B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7QK9MtmtjM_vtsr5v6bPpEM099MX0XT8',
    appId: '1:419482297256:web:6d844e15fad4475f0af39d',
    messagingSenderId: '419482297256',
    authDomain: 'flamingotar-32ba6.firebaseapp.com',
    projectId: 'flamingotar-32ba6',
    storageBucket: 'flamingotar-32ba6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7QK9MtmtjM_vtsr5v6bPpEM099MX0XT8',
    appId: '1:419482297256:web:6d844e15fad4475f0af39d',
    messagingSenderId: '419482297256',
    projectId: 'flamingotar-32ba6',
    storageBucket: 'flamingotar-32ba6.firebasestorage.app',
    androidClientId:
        'firebase-adminsdk-fbsvc@flamingotar-32ba6.iam.gserviceaccount.com',
    iosClientId:
        'firebase-adminsdk-fbsvc@flamingotar-32ba6.iam.gserviceaccount.com',
    iosBundleId: 'com.flamingolive.hus',
  );
}
